name: concord
description: Harmony in building.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.8.0
  firebase_storage: ^11.2.6
  firebase_analytics: ^10.4.5
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  google_sign_in: ^6.1.4
  flutter_secure_storage: ^8.0.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  path_provider: ^2.1.0
  image: ^4.0.17
  flutter_native_image: ^0.0.6+1
  provider: ^6.0.5
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  form_field_validator: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  image_painter: ^0.6.1
  audioplayers: ^5.2.1
  file_picker: ^8.0.0+1


dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter_icons:
  android: "icon_app"
  ios: true
  image_path: "assets/icons"
  adaptive_icon_background: "assets/icons/background_app.png"
  adaptive_icon_foreground: "assets/icons/foreground_app.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/placeholders/
    - assets/albumart/
    - assets/audio/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
